import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SuggestedSets } from "./SuggestedSets";
export function TraitList({ traits, suggestedSets, searchQuery, onSearchChange, sort, onSortChange, selectedIds, onAddTrait, assignedIds, onPreviewSet, onAddSet }) {
    const showBrowseState = !searchQuery.trim();
    const inputClass = "w-full rounded-md border border-slate-300 px-3 py-2 text-sm";
    return (_jsxs("div", { className: "flex min-w-0 flex-1 flex-col overflow-hidden", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2 border-b border-slate-200 p-3", children: [_jsx("input", { type: "search", className: inputClass, placeholder: "Search traits", value: searchQuery, onChange: (e) => onSearchChange(e.target.value), "aria-label": "Search traits" }), _jsxs("select", { className: inputClass, value: sort, onChange: (e) => onSortChange(e.target.value), "aria-label": "Sort traits", children: [_jsx("option", { value: "alphabetical", children: "Alphabetical" }), _jsx("option", { value: "most_used", children: "Most used" }), _jsx("option", { value: "recommended", children: "Recommended" })] })] }), _jsxs("div", { className: "flex-1 overflow-y-auto p-3", children: [showBrowseState && suggestedSets.length > 0 && (_jsx(SuggestedSets, { sets: suggestedSets, onPreview: onPreviewSet, onAddSet: onAddSet })), _jsx("div", { className: "space-y-1", children: traits.map((trait) => {
                            const isAssigned = assignedIds.has(trait.id);
                            const isSelected = selectedIds.has(trait.id);
                            const canAdd = !isAssigned && !isSelected;
                            return (_jsxs("div", { className: "flex items-center justify-between gap-3 rounded-md border border-slate-200 bg-white py-2 pl-3 pr-2", children: [_jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("div", { className: "font-medium text-slate-800", children: trait.name }), _jsx("div", { className: "mt-0.5 line-clamp-1 text-xs text-slate-500", children: trait.definition ?? "No description" }), _jsx("span", { className: "mt-1 inline-block rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600", children: trait.category })] }), _jsx("div", { className: "flex-shrink-0", children: isAssigned ? (_jsx("span", { className: "text-xs text-slate-400", children: "On board" })) : isSelected ? (_jsx("span", { className: "text-xs font-medium text-slate-600", children: "Added" })) : (_jsx("button", { type: "button", onClick: () => onAddTrait(trait.id), className: "rounded border border-slate-300 px-2 py-1 text-xs font-medium text-slate-700 hover:bg-slate-50", children: "+ Add" })) })] }, trait.id));
                        }) }), traits.length === 0 && (_jsx("p", { className: "py-4 text-center text-sm text-slate-500", children: "No traits match your filters or search." }))] })] }));
}
